{% set name = "datview" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/datview-{{ version }}.tar.gz
  sha256: bb701ac5ab44425e3c7639e5520170289cc77c36d60c53e0a8f9159b3caad100

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation 
  entry_points:
    - datview = datview.main:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - tk  
  run:
    - python >={{ python_min }}
    - h5py
    - hdf5plugin
    - pillow
    - matplotlib-base
    - tk        

test:
  imports:
    - datview
  commands:
    - datview --help  # [win]
    # Skipping GUI test on Linux/macOS (headless)...
  requires:
    - python {{ python_min }}
    - pip
    - matplotlib-base
    - tk

about:
  home: https://github.com/algotom/datview
  license: Apache-2.0
  license_file: LICENSE
  summary: GUI software for folder browsing and viewing text, image, Cine, and HDF files

extra:
  recipe-maintainers:
    - nghia-vo
