{% set name = "datview" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/datview-{{ version }}.tar.gz
  sha256: 34ff2df92ba6f17973fe59f3f48c90e285e78de945a17c74ba335ea85b9a2a82

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation 
  entry_points:
    - datview = datview.main:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - h5py
    - hdf5plugin
    - pillow
    - PySide6
    - pyqtgraph

test:
  imports:
    - datview
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/algotom/datview
  license: Apache-2.0
  license_file: LICENSE
  summary: GUI software for folder browsing and viewing text, image, Cine, and HDF files

extra:
  recipe-maintainers:
    - nghia-vo
